### ISSUE TITLE
testthat error

### ISSUE THREAD

**Issue by trotsiuk** [trotsiuk/r3PGmix#3]
Hi @florianhartig would you mind adding a simple working example to `testthat` part? E.g. `TRUE==TRUE`.
 Since you have added `test` directory I'm getting errors during the checking:

```
Error in test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure,  : 
  No matching test file in dir
Calls: test_check -> test_package_dir -> test_dir -> test_files
```

**Comment by trotsiuk** [comment]
Thank you for adding the test @florianhartig , however I still can't pass the `check` for the package. Would you have idea what is the issue?
I think also TravisCI is not passing due to this.

```
E  Running ‘testthat.R’ (434ms)
   Running the tests in ‘tests/testthat.R’ failed.
   Complete output:
     > library(testthat)
     > test_check("r3PGmix")
     Loading required package: r3PGmix
     Error in test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure,  : 
       No matching test file in dir
     Calls: test_check -> test_package_dir -> test_dir -> test_files
     Execution halted
```

**Comment by florianhartig** [comment]
Yes, I've seen this, there must be a problem in the test structure, although it's the same I use for DHARMa ... for the moment, just ignore this, but we should sort it out. The problem is that I still don't manage to run the model (due to the funny error), I have tried out various fortran compilers, but so far no luck. There should be a way though, it seems as if it's a compiler error.

Long story - I'll have to get the model running, and then it's also easier to sort out the tests.

**Comment by trotsiuk** [comment]
The issue was with the file naming. Chaining the test files to `test-...` solved the issue.
[Reference](https://github.com/r-lib/devtools/issues/2072)
